[package]
name = "bincache"
version = "0.2.0"
edition = "2021"
description = "ZitaneLabs binary cache."

[features]
default = ["tokio_rt_1"]
blocking = []
tokio_rt_1 = ["dep:tokio"]

[dependencies]
paste = "1.0.12"
thiserror = "1.0.40"
async-trait = { version = "0.1" }
tokio = { version = "1", features = ["rt", "fs", "io-util"], optional = true }

[dev-dependencies]
uuid = { version = "1.3.3", features = ["v4"] }
tokio = { version = "1", features = ["rt", "macros"] }
