[package]
name = "bincache"
version = "0.1.0"
edition = "2021"
description = "ZitaneLabs binary cache."

[features]

[dependencies]
paste = "1.0.12"
thiserror = "1.0.40"

[dev-dependencies]
uuid = { version = "1.3.3", features = ["v4"] }
